version: 2

before:
  hooks:
    - go mod tidy

builds:
  - id: dashbrr
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
      - freebsd
    goarch:
      - amd64
      - arm
      - arm64
    goarm:
      - "6"
    ignore:
      - goos: windows
        goarch: arm
      - goos: windows
        goarch: arm64
      - goos: darwin
        goarch: arm
      - goos: freebsd
        goarch: arm
      - goos: freebsd
        goarch: arm64
    main: ./cmd/dashbrr/main.go
    binary: dashbrr
    ldflags:
      - -s -w
      - -X github.com/autobrr/dashbrr/internal/buildinfo.Version={{.Version}}
      - -X github.com/autobrr/dashbrr/internal/buildinfo.Commit={{.Commit}}
      - -X github.com/autobrr/dashbrr/internal/buildinfo.Date={{.Date}}

archives:
  - id: dashbrr
    builds:
      - dashbrr
    format_overrides:
      - goos: windows
        format: zip
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else }}{{ .Arch }}{{ end }}

release:
  prerelease: auto
  footer: |
    **Full Changelog**: https://github.com/autobrr/dashbrr/compare/{{ .PreviousTag }}...{{ .Tag }}

    ## Docker images

    - `docker pull ghcr.io/autobrr/dashbrr:{{ .Tag }}`

    ## What to do next?

    - Read the [documentation](https://github.com/autobrr/dashbrr/blob/main/README.md)
    - Join our [Discord server](https://discord.gg/WQ2eUycxyT)

checksum:
  name_template: "{{ .ProjectName }}_{{ .Version }}_checksums.txt"

changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - Merge pull request
      - Merge remote-tracking branch
      - Merge branch
  groups:
    - title: "New Features"
      regexp: "^.*feat[(\\w)]*:+.*$"
      order: 0
    - title: "Bug fixes"
      regexp: "^.*fix[(\\w)]*:+.*$"
      order: 10
    - title: Other work
      order: 999

nfpms:
  - package_name: dashbrr
    homepage: https://autobrr.com
    maintainer: Autobrr <packages@autobrr.com>
    description: |-
      dashbrr is a modern dashboard for autobrr and related services.
    formats:
      - apk
      - deb
      - rpm
      - archlinux
