version: "3.8"

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: dashbrr
      POSTGRES_PASSWORD: dashbrr
      POSTGRES_DB: dashbrr_test
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U dashbrr"]
      interval: 5s
      timeout: 5s
      retries: 5
