services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: dashbrr
      POSTGRES_PASSWORD: dashbrr
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U dashbrr && psql -U dashbrr -d dashbrr_test -c 'SELECT 1'",
        ]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
    driver: local
